
/* ce face un angajat intr-o zi
E001
2026-07-15
*/
SELECT
 
    DE.EMPLOYEE_ID,
    DE.EMPLOYEE_NAME,
    DD.FULL_DATE,
    DAT.ACTIVITY_TYPE_NAME,
    DP.PROJECT_NAME,
    DT.TRAINING_NAME,
    FA.HOURS_WORKED,
    FA.SOURCE_SYSTEM
 
FROM FACT_ACTIVITY FA
 
JOIN DIM_EMPLOYEE DE
    ON FA.EMPLOYEE_KEY = DE.EMPLOYEE_KEY
 
JOIN DIM_DATE DD
    ON FA.DATE_KEY = DD.DATE_KEY
 
JOIN DIM_ACTIVITY_TYPE DAT
    ON FA.ACTIVITY_TYPE_KEY = DAT.ACTIVITY_TYPE_KEY
 
LEFT JOIN DIM_PROJECT DP
    ON FA.PROJECT_KEY = DP.PROJECT_KEY
 
LEFT JOIN DIM_TRAINING DT
    ON FA.TRAINING_KEY = DT.TRAINING_KEY
 
WHERE DE.EMPLOYEE_ID = '&EMPLOYEE_ID'
AND DD.FULL_DATE = TO_DATE('&SELECTED_DATE','YYYY-MM-DD');




/* ============================================================
   Monthly Training Participation Report
   ============================================================ */

SELECT
    DD.YEAR_NUMBER,
    DD.MONTH_NUMBER,
    DD.MONTH_NAME,
    DT.TRAINING_NAME,
    COUNT(*) AS PARTICIPANTS
FROM FACT_ACTIVITY FA
JOIN DIM_DATE DD
    ON FA.DATE_KEY = DD.DATE_KEY
JOIN DIM_TRAINING DT
    ON FA.TRAINING_KEY = DT.TRAINING_KEY
GROUP BY
    DD.YEAR_NUMBER,
    DD.MONTH_NUMBER,
    DD.MONTH_NAME,
    DT.TRAINING_NAME
ORDER BY
    DD.YEAR_NUMBER,
    DD.MONTH_NUMBER,
    DT.TRAINING_NAME;

    