INSERT INTO STG_TRAINING
(
    ATTENDANCE_ID,
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    GRADE,
    DISCIPLINE,
    LINE_MANAGER,
    DELIVERY_UNIT,
    TRAINING_DATE,
    TRAINING_NAME,
    CATEGORY,
    DURATION_HOURS,
    STATUS
)
SELECT
    ATTENDANCE_ID,
    UPPER(TRIM(EMPLOYEE_ID)),
    INITCAP(TRIM(EMPLOYEE_NAME)),
    INITCAP(TRIM(GRADE)),
    INITCAP(TRIM(DISCIPLINE)),
    INITCAP(TRIM(LINE_MANAGER)),
    TRIM(DELIVERY_UNIT),
    TO_DATE(TRAINING_DATE, 'MM/DD/YYYY'),
    INITCAP(TRIM(TRAINING_NAME)),
    INITCAP(TRIM(CATEGORY)),
    DURATION_HOURS,
    INITCAP(TRIM(STATUS))
FROM SRC_TRAINING;